services:
   service_api:
       build:
           context: .
       ports:
           - "8001:8000"
       command: >
           sh -c "python manage.py makemigrations && python manage.py migrate &&
                     python manage.py runserver 0.0.0.0:8000"
       volumes:
           - ./:/app
           - my_media:/files/media
       env_file:
           - .env
       depends_on:
           - db

   db:
       image: postgres:17-alpine3.19
       restart: always
       env_file:
           - .env
       ports:
           - "5432:5432"
       volumes:
           - db_airport_service_api:$PGDATA

volumes:
    db_airport_service_api:
    my_media: