# Generated by Django 5.1.5 on 2025-01-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air_service", "0002_rename_name_airplane_airplane_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flight",
            name="crew",
        ),
        migrations.AddField(
            model_name="flight",
            name="crew",
            field=models.ManyToManyField(related_name="flights", to="air_service.crew"),
        ),
    ]
