# Generated by Django 5.1.5 on 2025-01-18 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air_service", "0003_remove_flight_crew_flight_crew"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crew",
            options={"ordering": ["last_name", "first_name"]},
        ),
        migrations.AddField(
            model_name="ticket",
            name="order",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="air_service.order",
            ),
            preserve_default=False,
        ),
    ]
