# Generated by Django 5.1.5 on 2025-01-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air_service", "0004_alter_crew_options_ticket_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airplane",
            name="airplane_name",
            field=models.CharField(max_length=100),
        ),
    ]
