# Generated by Django 5.1.5 on 2025-01-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air_service", "0005_alter_airplane_airplane_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airplane",
            name="airplane_name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="airplanetype",
            name="type_name",
            field=models.CharField(max_length=100),
        ),
    ]
