# Generated by Django 5.1.5 on 2025-01-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air_service", "0006_alter_airplane_airplane_name_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="airplanetype",
            constraint=models.UniqueConstraint(
                fields=("type_name",), name="unique_type_name"
            ),
        ),
    ]
